### ISSUE TITLE
How can I stream logs from execute_command?

### ISSUE THREAD

**Issue by moredure** [jeffshantz/hyperkit#8]
I need some help.

**Comment by thewyzard44** [comment]
/bump

I'm willing to put some work into this if you're accepting PR's

**Comment by thewyzard44** [comment]
Actually the pieces may be there just not yet documented

https://github.com/jeffshantz/hyperkit/commit/1f9b343422c0b50400e1e27ec93396b57a2b060b#diff-cd78a742e1f49fe5e589350863daea57

the websocket functionality is what we're looking for

**Comment by Vanders** [comment]
The WS stuff on the client side can also be a bit complicated, but an example is https://github.com/Cyclid/Cyclid-lxd-plugin/blob/master/lib/cyclid/plugins/transport/lxdapi.rb#L71

**Comment by jeffshantz** [comment]
I unfortunately do not have time to work on this right now, but I'm happy to accept PRs.

**Comment by thewyzard44** [comment]
excellent!! Thank you for the head start @Vanders.  Assuming that since it has been done, I won't need a PR with this approach.  Thank you both!

**Comment by thewyzard44** [comment]
Success btw!  Although I wasn't happy with the performance of that base library so I wrote my own @ https://github.com/NexusSW/nio4r-websocket gem `nio4r-websocket`.  Feel free if you have any performance problems.  It is self-contained as well.
